#!/usr/bin/env python3
"""results.json -> a booktabs + siunitx LaTeX table.

One row per config. Best per column in bold - but only where the intervals
support the claim: a column whose leader overlaps a rival gets a footnote
saying so, and the rival is bolded too. The brief's rule is that an ordering
the intervals do not support must not be reported, and a bold number in a
table is a report of an ordering.

siunitx rather than hand-formatted numbers so the paper's own `\\sisetup`
controls precision and alignment, and so units live in the column spec
instead of being typed into 40 cells.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "benchmarks"))
sys.path.insert(0, str(REPO_ROOT / "analysis"))
import envelope as E   # noqa: E402
import style           # noqa: E402

GIB = 1024 ** 3

#: (heading, dotted path into a row, scale, decimals, lower-is-better)
COLUMNS: list[tuple[str, str, float, int, bool]] = [
    (r"bits/wt", "representation.effective_bits_per_weight", 1.0, 2, False),
    (r"mem.\ (\si{\gibi\byte})", "memory.peak_attributable_bytes", 1 / GIB, 1, True),
    (r"TTFT p90 (\si{\milli\second})", "latency.ttft_ms_p90", 1.0, 0, True),
    (r"decode (\si{\tokens\per\second})", "throughput.decode_tok_s_p50", 1.0, 1, False),
    (r"turn p90 (\si{\milli\second})", "latency.turn_ms_p90", 1.0, 0, True),
    (r"\si{\joule}/correct", "energy.marginal.j_per_correct_answer", 1.0, 1, True),
    (r"BFCL", "quality.suites.bfcl_overall", 100.0, 1, False),
    (r"MMLU", "quality.suites.mmlu", 100.0, 1, False),
]


def _leaf(row: dict, path: str) -> Any:
    node: Any = row
    for part in path.split("."):
        node = (node or {}).get(part) if isinstance(node, dict) else None
    return node


def _as_leaf(row: dict, path: str) -> dict[str, Any]:
    node = _leaf(row, path)
    if isinstance(node, dict):
        return node
    # representation.effective_bits_per_weight is a bare float by design -
    # it is an exact ratio of two counted quantities, not an estimate, so it
    # has no interval and wearing an envelope would only imply one.
    return {"value": node, "unit": "", "n": 1, "method": "exact"} if node is not None else {}


def pick_row(rows: list[dict], config_id: str, prompt_tokens: int | None) -> dict:
    """One representative condition per config.

    A table needs one row per config, so the condition has to be pinned, and
    pinning it is an editorial choice that belongs in the caption rather
    than hidden in the code - `--at-prompt-tokens` makes it explicit."""
    cand = [r for r in rows if r["config_id"] == config_id]
    if prompt_tokens is not None:
        exact = [r for r in cand if r["condition"]["prompt_tokens_target"] == prompt_tokens]
        if exact:
            return exact[0]
    return cand[0]


def build(rows: list[dict], prompt_tokens: int | None) -> str:
    configs = sorted({r["config_id"] for r in rows})
    picked = [pick_row(rows, c, prompt_tokens) for c in configs]

    # Which cells may be bolded: the leader, plus anyone whose interval
    # overlaps the leader's. A column where that set has more than one member
    # gets a footnote, because the ordering inside it is not supported.
    bold: dict[tuple[int, int], bool] = {}
    footnotes: list[str] = []
    for j, (head, path, _scale, _dp, lower_better) in enumerate(COLUMNS):
        leaves = [(i, _as_leaf(r, path)) for i, r in enumerate(picked)]
        have = [(i, lf) for i, lf in leaves if E.is_measured(lf)]
        if not have:
            continue
        best_i, best = min(have, key=lambda t: t[1]["value"]) if lower_better \
            else max(have, key=lambda t: t[1]["value"])
        tied = [i for i, lf in have if i == best_i or E.intervals_overlap(lf, best)]
        for i in tied:
            bold[(i, j)] = True
        if len(tied) > 1:
            names = ", ".join(style.label_for(picked[i]) for i in tied)
            footnotes.append(
                f"In the {head} column the 95\\% intervals of {names} overlap, so the "
                "ordering between them is not supported; all are shown in bold."
            )

    lines = [
        r"% generated by analysis/table.py - do not edit by hand",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Edge-LLM serving configurations on Jetson AGX Thor"
        + (f", measured at a {prompt_tokens}-token prompt" if prompt_tokens else "")
        + r". Best per column in bold; see notes for columns whose ordering the "
          r"95\% intervals do not support. Effective bits per weight is artifact bytes "
          r"per parameter and is the only column comparable across all three runtimes "
          r"without reference to the representation decomposition.}",
        r"\label{tab:configs}",
        r"\sisetup{table-number-alignment=center, detect-weight=true, detect-inline-weight=math}",
        r"\begin{tabular}{l" + "S" * len(COLUMNS) + "}",
        r"\toprule",
        "Configuration & " + " & ".join("{" + h + "}" for h, *_ in COLUMNS) + r" \\",
        r"\midrule",
    ]
    for i, row in enumerate(picked):
        cells = []
        for j, (_h, path, scale, dp, _lb) in enumerate(COLUMNS):
            lf = _as_leaf(row, path)
            if not E.is_measured(lf):
                cells.append("{--}")
                continue
            txt = f"{lf['value'] * scale:.{dp}f}"
            cells.append(r"\bfseries " + txt if bold.get((i, j)) else txt)
        name = style.FRAMEWORK_LABEL.get(row["framework"], row["framework"])
        rep = (row["representation"] or {}).get("comparability_class", "")
        lines.append(f"{{{name}, \\texttt{{{rep.replace('_', chr(92) + '_')}}}}} & "
                     + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    missing = [h for h, path, *_ in COLUMNS
               if not any(E.is_measured(_as_leaf(r, path)) for r in picked)]
    if missing:
        footnotes.append(
            "Columns " + ", ".join(missing) + " are empty: those quantities were not "
            "measured in this campaign. They are shown rather than dropped so the gap "
            "is visible in the table itself."
        )
    for note in footnotes:
        lines.append(r"\par\footnotesize " + note)
    lines.append(r"\end{table}")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("results", type=Path)
    ap.add_argument("--out", type=Path, default=REPO_ROOT / "output" / "figures" / "table_configs.tex")
    ap.add_argument("--at-prompt-tokens", type=int, default=512,
                    help="which condition the table reports; recorded in the caption")
    args = ap.parse_args()
    rows = json.loads(args.results.read_text())["rows"]
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(build(rows, args.at_prompt_tokens))
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
